# Generated by Django 6.0.2 on 2026-03-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_base_price'),
        ('services', '0003_service_user'),
    ]

    operations = [
    ]
