# Generated by Django 6.0.2 on 2026-03-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_merge_0003_alter_service_base_price_0003_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
