# Generated by Django 6.0.2 on 2026-02-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', max_length=10),
        ),
    ]
